target_link_libraries(
     EnvironmentMapping
        glad
        glfw3
        pthread
        dl
        X11
        freeimage
        opencv_core
        opencv_imgproc
        opencv_imgcodecs
        opencv_highgui
)